scrum\ScotchLodge\Entities\Distillery:
  type: entity
  repositoryClass: scrum\ScotchLodge\Entities\Repo\WhiskyRepo
  table: distillery
  id:
    id:
      type: integer
      generator:
        strategy: AUTO    
  
  oneToMany:
    dist_whiskys:
      targetEntity: Whisky
      mappedBy: distillery
      
    bottl_whiskys:
      targetEntity: Whisky
      mappedBy: bottlery
  
  fields:
    name:
      type: string
      length: 80
    address:
      type: string
      length: 255