scrum\ScotchLodge\Entities\Distillery:
  type: entity
  repositoryClass: scrum\ScotchLodge\Entities\Repo\WhiskyRepo
  table: distillery
  id:
    id:
      type: integer
      generator:
        strategy: AUTO    
  
  oneToMany:
    dist_whiskys:
      targetEntity: Whisky
      mappedBy: distillery
      
    bottl_whiskys:
      targetEntity: Whisky
      mappedBy: bottlery
  
  manyToOne:
    region:
      targetEntity: Region
      inversedBy: distilleries
      joinColumn:
        name: region_id
        referencedColumnName: id
    
    postcode:
      targetEntity: Postcode
      inversedBy: distilleries
      joinColumn:
        name: postcode_id
        referencedColumnName: id
  
  fields:
    name:
      type: string
      length: 80
    address:
      type: string
      length: 255