scrum\ScotchLodge\Entities\Whisky:
  type: entity
  repositoryClass: scrum\ScotchLodge\Entities\Repo\WhiskyRepo
  table: whisky
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    distillery:
      targetEntity: Distillery
      inversedBy: dist_whiskys
      joinColumn:
        name: distillery_id
        referencedColumnName: id
    
    bottlery:
      targetEntity: Distillery
      inversedBy: bottl_whiskys
      joinColumn:
        name: bottlery_id
        referencedColumnName: id
        
    barrel:
      targetEntity: Barrel
      inversedBy: barrel_whiskys
      joinColumn:
        name: barrel_id
        referencedColumnName: id
        
    event_whisky:
      targetEntity: EventWhisky
      
  manyToMany:
    events:
      targetEntity: Event
      inversedBy: event_whiskys
      joinTable:         
        name: event_whiskys
        joinColumns:
          whisky_id:
            referencedColumnName: id
        inverseJoinColumns:
          event_id:
            referencedColumnName: id

  oneToMany:
    scores:
      targetEntity: WhiskyScore
      mappedBy: whisky
    comments:
      targetEntity: CommentReview
      mappedBy: whisky

  fields:
    name:
      type: string
      length: 60    
    image_path:
      type: string
      length: 255
    price:
      type: integer
    age:
      type: integer
    alcohol:
      type: integer
    short_description:
      type: text
  