scrum\ScotchLodge\Entities\Category:
  type: entity
  #repositoryClass: scrum\ScotchLodge\Data\CountryRepo
  table: category  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  oneToMany:
    scores:
      targetEntity: WhiskyScores
      mappedBy: category
    
        
  fields:
    category:
      type: string
      length: 45        